graphTest: HW4.o Graph.o
	g++ -o graphTest HW4.o Graph.o
HW4.o: HW4.cpp Graph.h
	g++ -c -Wall -Werror -pedantic -std=c++11 HW4.cpp
Graph.o: Graph.cpp Graph.h
	g++ -c -Wall -Werror -pedantic -std=c++11 Graph.cpp
